### ISSUE TITLE
Support the ability to pass semver specs

### ISSUE THREAD

**Issue by stack72** [pulumi/action-install-pulumi-cli#18]
```
- name: Install pulumi
  uses: pulumi/action-install-pulumi-cli@v1.0.2
  with:
    pulumi-version: ^2.0.0
```
