### ISSUE TITLE
Major version mismatch. You are using Pulumi CLI version 3.0.0 with Automation SDK v2. Please update the SDK.

### ISSUE THREAD

**Issue by wayne-o** [pulumi/action-install-pulumi-cli#19]
Needs updating

`Major version mismatch. You are using Pulumi CLI version 3.0.0 with Automation SDK v2. Please update the SDK.`

**Comment by stack72** [comment]
Hi @wayne-o 

I just pointed out to another user that they are not pinning theoir version of the CLI as follows:

```
- name: Install pulumi
  uses: pulumi/action-install-pulumi-cli@v1
  with:
    pulumi-version: 2.25.2 (or whatever version)
```

so this action will bring in latest

This means when you are using the pulumi/action@v2 (which is bound to the v3 SDK) then you will get this error

Your 2 options are:

1. Upgrade to pulumi/action@v3
2. Pin a CLI version

Both will work for you BUT you need to make sure you don't mismatch CLI and SDK versions as they are incompatible

Please let me know if you have any issues

Paul
